### ISSUE TITLE
Update the docs to refer to Raspberry Pi OS

### ISSUE THREAD

**Issue by jimbobbennett** [microsoft/rpi-resources#7]
Raspbian has been renamed to Raspberry Pi OS (see https://www.raspberrypi.org/blog/latest-raspberry-pi-os-update-may-2020/), so the docs need to be updated to reflect this name change including in the text and screenshots.

**Comment by adiazulay** [comment]
This issue is fixed with commit [9fb62b9](https://github.com/microsoft/rpi-resources/commit/9fb62b93e2b8f406db252a33f519db1b4bf7a4f8)
